### ISSUE TITLE
Getting error while trying to connect to DB

### ISSUE THREAD

**Issue by ngarg-panw** [singlestore-labs/start-with-singlestore-python-kubernetes#2]
Hi, I copied your main.tf and was trying to run it but it is throwing the following error:  

File "/Users/ngarg/PycharmProjects/memsqlKafka/startup_try.py", line 71, in <module>
    main()
  File "/Users/ngarg/PycharmProjects/memsqlKafka/startup_try.py", line 15, in main
    conn = database.connect(host=HOST, port=PORT, user=USER, password=PASSWORD, database=DATABASE)
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 19, in connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 62, in __init__
    self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 93, in reconnect
    conn = _mysql.connect(**self._db_args)
TypeError: 'db' is an invalid keyword argument for connect()

**Comment by robrich** [comment]
I don't see `db` in `main.py`. Can you post `startup_try.py` as a gist?

**Comment by ngarg-panw** [comment]
@robrich I was able to resolve the above error by renaming "db" to "database" and "passwd" to "password" in database.py file from the memsql library. Looks like there is some renaming done in SQLClient which has not been reflected in the respective file.

memsql version 3.1.0 and SQLClient version 2.1.0

After making those changes locally, now I am getting the "handshake" error:
`Traceback (most recent call last):
  File "/Users/user/PycharmProjects/memsqlKafka/startup_try.py", line 72, in <module>
    main()
  File "/Users/user/PycharmProjects/memsqlKafka/startup_try.py", line 16, in main
    conn = database.connect(host=HOST, port=PORT, database=DATABASE, user=USER, password=PASSWORD)
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 19, in connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 62, in __init__
    self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 93, in reconnect
    conn = _mysql.connect(**self._db_args)
MySQLdb._exceptions.OperationalError: (2012, 'Error in server handshake')`

I am able to connect to the db using the same creds details via tableplus. But via python script, its just not working.

it will also help if you can share which versions of memsql and SqlClient did you use?
